name: Manual test

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    env:
      AWS_CONFIG_FILE: .github/workflows/credentials
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: chay code
        run: |
          python3.9 --version
          ls -la
          python3.9 cloud-manage-test-cases/create_command.py
